// Problems from projecteuler.net

// Problem 1
// 'Multiples of 3 and 5'
// Description:
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
// The sum of these multiples is 23.

// Task:
// Find the sum of all the multiples of 3 or 5 below 1000.

const multiples = (x, y) => {
    let sum = 0
    for (let i = 0; i < 1000; i++) {
        if (i % x === 0 || i % y === 0) {
            sum += i
        }
    }
    console.log(`The sum of all multiples of 3 or 5 below 1000 is: ${sum}.`)
    return sum
}

// multiples(3, 5)


//-----------------------------------------------------------------------------------------------


// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

// Task:
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// Find the sum of the even-valued terms.

const fibonacci = () => {
    
}